### ISSUE TITLE
多cmd id对应一个Actor时，只有一个Actor对象被创建，但会被Init多次

### ISSUE THREAD

**Issue by yuanboshe** [Bwar/Nebula#23]
> [WARNING][../src/actor/ActorFactory.hpp:86][Create] no CreateObject found for "nebtcp::CmdHello" 
> [INFO][../src/actor/ActorBuilder.hpp:287][NewActor] "nebtcp::CmdHello" created by NewActor() instead.
> [INFO][../src/actor/ActorBuilder.cpp:1204][BootLoadCmd] succeed in loading nebtcp::CmdHello with cmd 1001
> [WARNING][../src/actor/ActorFactory.hpp:86][Create] no CreateObject found for "nebtcp::CmdHello"
> [INFO][../src/actor/ActorBuilder.hpp:287][NewActor] "nebtcp::CmdHello" created by NewActor() instead.
> [INFO][../src/actor/ActorBuilder.cpp:1204][BootLoadCmd] succeed in loading nebtcp::CmdHello with cmd 1003

不确定是设计如此，还是应该只被Init一次。

代码逻辑在ActorBuilder::MakeSharedActor()内。

**Comment by Bwar** [comment]
ActorBuilder::MakeSharedActor() 每次调用都创建了新的对象，多个cmd id对应同一个Actor类时也是一样的，创建了与cmd id对应的多个对象并执行了Init()
